name: houzzdat_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Logic
  supabase_flutter: ^2.6.0
  provider: ^6.1.1
  
  # Features (Audio & UI)
  record: ^5.1.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  intl: ^0.19.0
  
  # Web Support helpers
  web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # This MUST be here, not under dependencies, for icons to work.
  uses-material-design: true